// flow-typed signature: 1c48101edd55ab72d2290c1546b3b0bb
// flow-typed version: <<STUB>>/react-native-modalbox_v1.4.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-modalbox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-modalbox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-modalbox/index' {
  declare module.exports: $Exports<'react-native-modalbox'>;
}
declare module 'react-native-modalbox/index.js' {
  declare module.exports: $Exports<'react-native-modalbox'>;
}
