// flow-typed signature: c7d533427c0dcd44283bc6d010d0c75d
// flow-typed version: <<STUB>>/react-intl-native_v^2.1.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-intl-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-intl-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-intl-native/dist/react-intl-native.es2015' {
  declare module.exports: any;
}

declare module 'react-intl-native/dist/react-intl-native' {
  declare module.exports: any;
}

declare module 'react-intl-native/src/FormattedDate' {
  declare module.exports: any;
}

declare module 'react-intl-native/src/FormattedHTMLMessage' {
  declare module.exports: any;
}

declare module 'react-intl-native/src/FormattedMessage' {
  declare module.exports: any;
}

declare module 'react-intl-native/src/FormattedMessage.test' {
  declare module.exports: any;
}

declare module 'react-intl-native/src/FormattedNumber' {
  declare module.exports: any;
}

declare module 'react-intl-native/src/FormattedPlural' {
  declare module.exports: any;
}

declare module 'react-intl-native/src/FormattedRelative' {
  declare module.exports: any;
}

declare module 'react-intl-native/src/FormattedTime' {
  declare module.exports: any;
}

declare module 'react-intl-native/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-intl-native/dist/react-intl-native.es2015.js' {
  declare module.exports: $Exports<'react-intl-native/dist/react-intl-native.es2015'>;
}
declare module 'react-intl-native/dist/react-intl-native.js' {
  declare module.exports: $Exports<'react-intl-native/dist/react-intl-native'>;
}
declare module 'react-intl-native/src/FormattedDate.js' {
  declare module.exports: $Exports<'react-intl-native/src/FormattedDate'>;
}
declare module 'react-intl-native/src/FormattedHTMLMessage.js' {
  declare module.exports: $Exports<'react-intl-native/src/FormattedHTMLMessage'>;
}
declare module 'react-intl-native/src/FormattedMessage.js' {
  declare module.exports: $Exports<'react-intl-native/src/FormattedMessage'>;
}
declare module 'react-intl-native/src/FormattedMessage.test.js' {
  declare module.exports: $Exports<'react-intl-native/src/FormattedMessage.test'>;
}
declare module 'react-intl-native/src/FormattedNumber.js' {
  declare module.exports: $Exports<'react-intl-native/src/FormattedNumber'>;
}
declare module 'react-intl-native/src/FormattedPlural.js' {
  declare module.exports: $Exports<'react-intl-native/src/FormattedPlural'>;
}
declare module 'react-intl-native/src/FormattedRelative.js' {
  declare module.exports: $Exports<'react-intl-native/src/FormattedRelative'>;
}
declare module 'react-intl-native/src/FormattedTime.js' {
  declare module.exports: $Exports<'react-intl-native/src/FormattedTime'>;
}
declare module 'react-intl-native/src/index.js' {
  declare module.exports: $Exports<'react-intl-native/src/index'>;
}
